### ISSUE TITLE
LLVM missing while selecting only one target driver which does not require LLVM

### ISSUE THREAD

**Issue by timemaster5** [dev-0x7C6/meta-mesa#1]
If I set PACKAGECONFIG_append_pn-mesa = " i915", this error appears:
`meson.build:1484:2: ERROR: Problem encountered: The following drivers require LLVM: Radv, RadeonSI, SWR. One of these is enabled, but LLVM is disabled.` 

If there is another additional driver which requires llvm like gallium-llvm added to the list, everything is ok.

My architecture is intel-core2-3 and I am on zeus branch

**Comment by dev-0x7C6** [comment]
If you're appending (by _ operator) you need to add additional space before string literal. (Not sure if this a typo in bug report)

This should be corrected to ```PACKAGECONFIG_append_pn-mesa = " i915"```

Can you give me output of ```MACHINE="intel-core2-32" bitbake -e mesa | grep ^PACKAGECONFIG```

**Comment by timemaster5** [comment]
> If you're appending (by _ operator) you need to add additional space before string literal. (Not sure if this a typo in bug report)
> 
> This should be corrected to `PACKAGECONFIG_append_pn-mesa = " i915"`
> 
> Can you give me output of `MACHINE="intel-core2-32" bitbake -e mesa | grep ^PACKAGECONFIG`

I am sorry, this was a typo.. :) fixed in the original post, I did it right in my config.

> Can you give me output of `MACHINE="intel-core2-32" bitbake -e mesa | grep ^PACKAGECONFIG`

here is the output

PACKAGECONFIG="vulkan wayland                    opengl egl gles gbm dri gallium                                                            elf-tls                    lto 		      i915            "
PACKAGECONFIG_CONFARGS=" -Ddri=true -Ddri-drivers=,r100,r200,nouveau,i965  -Ddri3=false -Degl=true -Delf-tls=true -Dgallium-drivers=swrast,virgl,i915  -Dllvm=false -Dgbm=true -Dgles1=true -Dgles2=true -Dopengl=true -Dosmesa=none -Dlibunwind=false  -Dgallium-va=false  -Dgallium-vdpau=false -Dvulkan-drivers=,intel,amd -Dglx=disabled  -Dgallium-xa=false -Dgallium-xvmc=false"
PACKAGECONFIG_class-native="gbm dri egl opengl elf-tls"
PACKAGECONFIG_class-nativesdk="gbm dri egl opengl elf-tls"
PACKAGECONFIG_class-target="vulkan wayland                    opengl egl gles gbm dri gallium                                                            elf-tls                    lto "

**Comment by dev-0x7C6** [comment]
Ok I think I found the problem. This was caused by `vulkan` `PACKAGECONFIG` that silently pulling amdgpu drivers, even if no amd driver was specified.

This commit 113cb97476a5c9475f06995c10553f77a4f9d3c1 should fix problem, but I tested this only for dunfell builds.

I also spotted that `nouveau` and `rXXX` drivers are included to DRI drivers and there is no condition also. I'll fix that later.

**Comment by timemaster5** [comment]
Thank you, I can confirm that is works even on zeus branch.
 Still have to test your dunfell build with the LTO to see the performance impact :)

**Comment by dev-0x7C6** [comment]
> Still have to test your dunfell build with the LTO to see the performance impact :)

I don't have a proper 3d benchmark environment to provide any information on that. But some Mesa binaries was slightly reduced in size. I'm not sure if Mesa developers using some more advanced LTO flags (and other switches). For this mesa recipes I'm just using basic ```-flto=<core_number>``` parameter, hope it's enough to achieve notable performance gain.
